# Generated by Django 4.0.4 on 2022-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('MeetingId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Agenda', models.TextField()),
                ('Venue', models.CharField(max_length=200)),
                ('Guests', models.TextField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Minutes', models.TextField()),
                ('Attachments', models.FileField(upload_to='attachments')),
            ],
            options={
                'db_table': 'Meeting',
            },
        ),
    ]
