# Generated by Django 4.0.4 on 2022-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='Attachments',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='Minutes',
            field=models.TextField(null=True),
        ),
    ]
