# Generated by Django 4.0.4 on 2022-05-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_attachments_alter_meeting_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='Agenda',
            new_name='agenda',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='EndTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='Guests',
            new_name='guests',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='MeetingId',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='StartTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='Venue',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='Attachments',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='Minutes',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='meeting',
        ),
    ]
