# Generated by Django 4.0.4 on 2022-05-26 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0005_alter_meeting_attachments_alter_meeting_meeting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=meeting.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='minutes',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='files',
            field=models.ManyToManyField(to='meeting.meetingfile'),
        ),
    ]
