# Generated by Django 4.0.4 on 2022-05-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_meetingfile_remove_meeting_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='files',
        ),
        migrations.AddField(
            model_name='meetingfile',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting'),
            preserve_default=False,
        ),
    ]
