# Generated by Django 4.0.4 on 2022-05-26 04:19

from django.db import migrations, models
import django.db.models.deletion
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_remove_meeting_files_meetingfile_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingfile',
            name='file',
            field=models.FileField(default='', upload_to=meeting.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingfile',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingfiles', to='meeting.meeting'),
        ),
    ]
