# Generated by Django 4.0.4 on 2022-05-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_meetingfile_file_alter_meetingfile_meeting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingfile',
            table='meeting_file',
        ),
    ]
