# Generated by Django 4.0.4 on 2022-05-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_alter_meetingfile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingfile',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_files', to='meeting.meeting'),
        ),
    ]
