# Generated by Django 4.0.4 on 2022-05-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_alter_meetingfile_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_id',
            new_name='id',
        ),
    ]
