# Generated by Django 4.0.4 on 2022-05-27 13:26

from django.db import migrations, models
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_alter_meetingfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=meeting.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MeetingFile',
        ),
    ]
