# Generated by Django 4.0.4 on 2022-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_meeting_attachments_meeting_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
