# Generated by Django 4.0.4 on 2022-05-27 14:36

from django.db import migrations, models
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_alter_meeting_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=meeting.models.user_directory_path),
        ),
    ]
